#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
# Alan Viars

import argparse
import json
from jdt.jsondir2ndjson import jsondir2ndjson


if __name__ == "__main__":

    # Parse args
    parser = argparse.ArgumentParser(
        description='Load in directory which contains JSON docs and convert it into a single NDJSON file.')
    parser.add_argument(
        dest='input_JSON_dir',
        action='store',
        help='Input the JSON dir to load here')
    parser.add_argument(
        dest='output_NDJSON_file',
        action='store',
        help="Enter the output filename")
    args = parser.parse_args()

    result = jsondir2ndjson(args.input_JSON_dir, args.output_NDJSON_file)

    # output the JSON transaction summary
    print(json.dumps(result, indent=4))
