#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4
# Alan Viars

import argparse
from jdt.split_large_files import split_large_files


if __name__ == "__main__":

    # Parse args
    parser = argparse.ArgumentParser(
        description='Split a large file into many based on a specified number of lines.')
    parser.add_argument(
        dest='input_file',
        action='store',
        help='Input file to be split')
    parser.add_argument(
        dest='number_of_lines_per_file',
        action='store',
        help="Enter the numbert of lines per file.")

    args = parser.parse_args()
    split_large_files(args.input_file, int(args.number_of_lines_per_file))



